# fly.toml app configuration file generated for linkshelf on 2023-07-30T01:24:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linkshelf"
primary_region = "iad"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health_check"
